# Generated by Django 3.2.5 on 2021-07-30 09:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountId', models.AutoField(primary_key=True, serialize=False)),
                ('ConnectionStatus', models.BooleanField(default=False)),
                ('SpendLimit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
            ],
            options={
                'verbose_name': 'Account',
            },
        ),
        migrations.CreateModel(
            name='AssetDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssetId', models.CharField(max_length=15)),
                ('EntryPrice', models.FloatField()),
                ('CurrentMarketPrice', models.FloatField(default=Decimal('0'))),
                ('EntryPriceDiff', models.FloatField(default=Decimal('0'))),
                ('AvgEntryPoint1', models.FloatField(default=Decimal('0'))),
                ('Avg1Diff', models.FloatField(default=Decimal('0'))),
                ('AvgEntryPoint2', models.FloatField(default=Decimal('0'))),
                ('Avg2Diff', models.FloatField(default=Decimal('0'))),
                ('TargetPrice', models.FloatField(default=Decimal('0'))),
                ('Quantity', models.IntegerField(default=0)),
                ('Sector', models.CharField(max_length=50)),
                ('Industry', models.CharField(max_length=50)),
                ('Beta', models.FloatField(default=Decimal('0'))),
                ('NextEarningDate', models.DateTimeField(blank=True, null=True)),
                ('AccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeNext.account')),
            ],
            options={
                'verbose_name': 'AssetDetails',
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('BrokerId', models.AutoField(primary_key=True, serialize=False)),
                ('BrokerName', models.CharField(max_length=50)),
                ('BrokerAccountId', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Broker',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('EmailId', models.EmailField(max_length=100)),
                ('Mobile', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RealizePL', models.FloatField()),
                ('UnRealizedPL', models.FloatField()),
                ('RealizedPLPercent', models.FloatField()),
                ('DaysInTrade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Reporting',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('StrategyId', models.AutoField(primary_key=True, serialize=False)),
                ('StrategyName', models.CharField(max_length=15)),
                ('StrategyType', models.IntegerField(choices=[(1, 'Limit Trade'), (2, 'Auto Trade'), (3, 'Direct Trade')])),
                ('MaxInvestment', models.FloatField()),
                ('TargetPrice', models.FloatField()),
                ('AvgPoint1', models.FloatField()),
                ('AvgPoint2', models.FloatField()),
                ('maxTradePerDay', models.IntegerField(default=0)),
                ('maxTradePerSector', models.IntegerField(default=0)),
                ('TotalFundAllocated', models.FloatField()),
            ],
            options={
                'verbose_name': 'Strategy',
            },
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('TradeId', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('AssetPriceAEntry', models.FloatField()),
                ('AssetPriceAtClose', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Status', models.IntegerField()),
                ('MBP', models.FloatField()),
                ('CBP', models.FloatField()),
                ('Commissions', models.FloatField()),
                ('AvgDate1', models.DateTimeField()),
                ('AvgDate2', models.DateTimeField()),
                ('AvgDate3', models.DateTimeField()),
                ('TradeAverage', models.BooleanField()),
                ('AccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeNext.account')),
                ('AssetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeNext.assetdetails')),
                ('StrategyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeNext.strategy')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeNext.customer')),
            ],
            options={
                'verbose_name': 'Trade',
            },
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='StrategyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeNext.strategy'),
        ),
        migrations.AddField(
            model_name='account',
            name='BrokerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeNext.broker'),
        ),
        migrations.AddField(
            model_name='account',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeNext.customer'),
        ),
    ]
