# Generated by Django 3.2.5 on 2021-08-05 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeNext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='AccountName',
            field=models.CharField(default='Hello', max_length=50),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='LastUpdatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
