# Generated by Django 2.1.15 on 2021-07-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeNext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetails',
            name='Industry',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='NextEarningDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assetdetails',
            name='Sector',
            field=models.CharField(max_length=50),
        ),
    ]
