# Generated by Django 2.1.15 on 2021-07-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeNext', '0002_auto_20210716_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetails',
            name='NextEarningDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
