# Generated by Django 3.2.5 on 2021-07-19 08:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeNext', '0003_auto_20210716_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetails',
            name='CurrentMarketPrice',
            field=models.FloatField(default=Decimal('0')),
        ),
    ]
