# Generated by Django 3.2.5 on 2021-07-19 08:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeNext', '0004_assetdetails_currentmarketprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetails',
            name='Avg1Diff',
            field=models.FloatField(default=Decimal('0')),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='Avg2Diff',
            field=models.FloatField(default=Decimal('0')),
        ),
        migrations.AddField(
            model_name='assetdetails',
            name='EntryPriceDiff',
            field=models.FloatField(default=Decimal('0')),
        ),
    ]
