# Generated by Django 3.2.5 on 2021-07-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeNext', '0005_auto_20210719_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdetails',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
