# Generated by Django 3.2.5 on 2021-07-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeNext', '0006_assetdetails_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='maxTradePerDay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='maxTradePerSector',
            field=models.IntegerField(default=0),
        ),
    ]
